#!/bin/bash

${1} --install-extension adobeexl.adobe-markdown-authoring
${1} --install-extension amazonwebservices.amazon-q-vscode
${1} --install-extension amazonwebservices.aws-toolkit-vscode
${1} --install-extension antfu.goto-alias
${1} --install-extension asciidoctor.asciidoctor-vscode
${1} --install-extension davidanson.vscode-markdownlint
${1} --install-extension dbaeumer.vscode-eslint
${1} --install-extension denoland.vscode-deno
${1} --install-extension docker.docker
${1} --install-extension docsmsft.docs-markdown
${1} --install-extension docsmsft.docs-yaml
${1} --install-extension github.copilot
${1} --install-extension github.copilot-chat
${1} --install-extension github.remotehub
${1} --install-extension github.vscode-github-actions
${1} --install-extension github.vscode-pull-request-github
${1} --install-extension gitlab.gitlab-workflow
${1} --install-extension golang.go
${1} --install-extension google.gemini-cli-vscode-ide-companion
${1} --install-extension google.geminicodeassist
${1} --install-extension googlecloudtools.cloudcode
${1} --install-extension hashicorp.terraform
${1} --install-extension mermaidchart.vscode-mermaid-chart
${1} --install-extension ms-azure-load-testing.microsoft-testing
${1} --install-extension ms-azuretools.azure-dev
${1} --install-extension ms-azuretools.vscode-azure-github-copilot
${1} --install-extension ms-azuretools.vscode-azure-mcp-server
${1} --install-extension ms-azuretools.vscode-azureappservice
${1} --install-extension ms-azuretools.vscode-azurecontainerapps
${1} --install-extension ms-azuretools.vscode-azurefunctions
${1} --install-extension ms-azuretools.vscode-azureresourcegroups
${1} --install-extension ms-azuretools.vscode-azurestaticwebapps
${1} --install-extension ms-azuretools.vscode-azurestorage
${1} --install-extension ms-azuretools.vscode-azurevirtualmachines
${1} --install-extension ms-azuretools.vscode-containers
${1} --install-extension ms-azuretools.vscode-cosmosdb
${1} --install-extension ms-azuretools.vscode-docker
${1} --install-extension ms-ceintl.vscode-language-pack-ja
${1} --install-extension ms-python.autopep8
${1} --install-extension ms-python.black-formatter
${1} --install-extension ms-python.debugpy
${1} --install-extension ms-python.flake8
${1} --install-extension ms-python.isort
${1} --install-extension ms-python.mypy-type-checker
${1} --install-extension ms-python.pylint
${1} --install-extension ms-python.python
${1} --install-extension ms-python.vscode-pylance
${1} --install-extension ms-python.vscode-python-envs
${1} --install-extension ms-toolsai.jupyter
${1} --install-extension ms-toolsai.jupyter-keymap
${1} --install-extension ms-toolsai.jupyter-renderers
${1} --install-extension ms-toolsai.vscode-jupyter-cell-tags
${1} --install-extension ms-toolsai.vscode-jupyter-slideshow
${1} --install-extension ms-vscode.azure-repos
${1} --install-extension ms-vscode.cmake-tools
${1} --install-extension ms-vscode.cpptools
${1} --install-extension ms-vscode.cpptools-extension-pack
${1} --install-extension ms-vscode.cpptools-themes
${1} --install-extension ms-vscode.live-server
${1} --install-extension ms-vscode.makefile-tools
${1} --install-extension ms-vscode.remote-repositories
${1} --install-extension ms-vscode.vscode-node-azure-pack
${1} --install-extension ms-vscode.vscode-typescript-next
${1} --install-extension ms-vsliveshare.vsliveshare
${1} --install-extension ms-windows-ai-studio.windows-ai-studio
${1} --install-extension nuxt.mdc
${1} --install-extension nuxtr.nuxt-vscode-extentions
${1} --install-extension nuxtr.nuxtr-vscode
${1} --install-extension openai.chatgpt
${1} --install-extension redhat.vscode-yaml
${1} --install-extension rust-lang.rust-analyzer
${1} --install-extension teamsdevapp.vscode-ai-foundry
${1} --install-extension vue.volar
${1} --install-extension xdebug.php-debug
${1} --install-extension xdebug.php-pack
${1} --install-extension zobo.php-intellisense